### ISSUE TITLE
Minor issue: tailing whitespace in application_area_de

### ISSUE THREAD

**Issue by Lutzeli** [agroscope-ch/srppphist#1]
"application_area_de" contains the entry "Obstbau allg. " with a tailing whitespace. This is a minor issue and does not necesserely need to be adressed. I just thought you would like to know.

**Comment by jranke** [comment]
Thanks for the comment. I will keep this open for the moment, as I am considering to use `trimws()` on fields read in from the XML file. Recently we discovered a case in another field, I think it was an active substance name.
